// GENERADO por scripts/authz-registry.mjs — no editar a mano.
// Regenerar: npm run authz:registry. Un export sin envolver aquí = error de tsc.
// Nadie importa este archivo en runtime: existe solo para que tsc lo compruebe.
import type { Modulo } from "./tipos";

import * as m0 from "@/app/(auth)/login/actions";
import * as m1 from "@/app/(auth)/recuperar-password/actions";
import * as m2 from "@/app/(tenant)/[slug]/buscar-actions";
import * as m3 from "@/app/(tenant)/[slug]/caja/actions";
import * as m4 from "@/app/(tenant)/[slug]/caja/autorizaciones-actions";
import * as m5 from "@/app/(tenant)/[slug]/caja/corte-actions";
import * as m6 from "@/app/(tenant)/[slug]/caja/mp-actions";
import * as m7 from "@/app/(tenant)/[slug]/checkins/actions";
import * as m8 from "@/app/(tenant)/[slug]/checkins/scanner/actions";
import * as m9 from "@/app/(tenant)/[slug]/clases/[sesionId]/actions";
import * as m10 from "@/app/(tenant)/[slug]/comunicaciones/campanas/actions";
import * as m11 from "@/app/(tenant)/[slug]/comunicaciones/whatsapp/actions";
import * as m12 from "@/app/(tenant)/[slug]/configuracion/api/actions";
import * as m13 from "@/app/(tenant)/[slug]/configuracion/cajas/actions";
import * as m14 from "@/app/(tenant)/[slug]/configuracion/clases/actions";
import * as m15 from "@/app/(tenant)/[slug]/configuracion/gym/actions";
import * as m16 from "@/app/(tenant)/[slug]/configuracion/marca/actions";
import * as m17 from "@/app/(tenant)/[slug]/configuracion/pagos/actions";
import * as m18 from "@/app/(tenant)/[slug]/configuracion/planes/actions";
import * as m19 from "@/app/(tenant)/[slug]/configuracion/plantillas/actions";
import * as m20 from "@/app/(tenant)/[slug]/configuracion/promociones/actions";
import * as m21 from "@/app/(tenant)/[slug]/configuracion/staff/actions";
import * as m22 from "@/app/(tenant)/[slug]/configuracion/tags/actions";
import * as m23 from "@/app/(tenant)/[slug]/configuracion/whatsapp/actions";
import * as m24 from "@/app/(tenant)/[slug]/inventario/actions";
import * as m25 from "@/app/(tenant)/[slug]/miembros/[id]/creditos-actions";
import * as m26 from "@/app/(tenant)/[slug]/miembros/[id]/membresia-actions";
import * as m27 from "@/app/(tenant)/[slug]/miembros/[id]/nutricion-actions";
import * as m28 from "@/app/(tenant)/[slug]/miembros/[id]/renovar-actions";
import * as m29 from "@/app/(tenant)/[slug]/miembros/actions";
import * as m30 from "@/app/(tenant)/[slug]/miembros/importar/actions";
import * as m31 from "@/app/(tenant)/[slug]/miembros/qr-actions";
import * as m32 from "@/app/(tenant)/[slug]/notas/actions";
import * as m33 from "@/app/(tenant)/[slug]/notificaciones-actions";
import * as m34 from "@/app/(tenant)/[slug]/onboarding/actions";
import * as m35 from "@/app/(tenant)/[slug]/prospectos/actions";
import * as m36 from "@/app/(tenant)/[slug]/reportes/financiero/actions";
import * as m37 from "@/app/(tenant)/[slug]/suspendida/actions";
import * as m38 from "@/app/(tenant)/[slug]/terminos-actions";
import * as m39 from "@/app/admin/(panel)/actions";
import * as m40 from "@/app/admin/(panel)/cuenta/actions";
import * as m41 from "@/app/admin/(panel)/eventos/actions";
import * as m42 from "@/app/admin/(panel)/solicitudes/actions";
import * as m43 from "@/app/admin/(panel)/tenants/[tenantId]/actions";
import * as m44 from "@/app/admin/login/actions";
import * as m45 from "@/app/auth/accept-invite/actions";
import * as m46 from "@/app/kiosco/[slug]/actions";
import * as m47 from "@/app/portal/[slug]/actions";
import * as m48 from "@/app/portal/[slug]/clases/actions";
import * as m49 from "@/app/portal/[slug]/congelar-actions";
import * as m50 from "@/app/portal/[slug]/login/actions";
import * as m51 from "@/app/portal/[slug]/opinion-actions";
import * as m52 from "@/app/portal/[slug]/renovar/actions";

export const panel = [m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20, m21, m22, m23, m24, m25, m26, m27, m28, m29, m30, m31, m32, m33, m34, m35, m36, m37, m38] satisfies ReadonlyArray<Modulo<"panel">>;
export const portal = [m47, m48, m49, m50, m51, m52] satisfies ReadonlyArray<Modulo<"portal">>;
export const kiosco = [m46] satisfies ReadonlyArray<Modulo<"kiosco">>;
export const admin = [m39, m40, m41, m42, m43, m44] satisfies ReadonlyArray<Modulo<"admin">>;
export const anon = [m0, m1, m45] satisfies ReadonlyArray<Modulo<"anon">>;
